### PR TITLE
Small refactoring. Fixed few bugs. Added new features

### PR DESCRIPTION
**Pull request by Glorian**
Features
===========

* Opportunity to set custom charset to parse result (default - UTF-8)
```php
$googleUrl = new \GoogleUrl();
$googleUrl->setEncoding('UTF-8');
....
```
* Now you can add your user agents to pool. It will randomly changed before each request.
```php
$userAgents = array(
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10; rv:33.0) Gecko/20100101 Firefox/33.0',
);

$googleUrl = new \GoogleUrl();

// Set new array of user agents
$googleUrl->setUserAgents($userAgents);

// You can add new user agent
$googleUrl->addUserAgent('Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0');
```
* Added new google parameter "near" for manual set of results location.
```php
$googleUrl = new \GoogleUrl();
$googleUrl->searchTerm('buy pizza');
$googleUrl->setNear('new york');

// Request Url: https://www.google.com/search?q=buy%20pizza&start=0&num=10&complete=0&pws=0&hl=en&lr=lang_en&near=new%20york
// Google results will be located in New York
```

Other changes
===========
1. Added PHPDoc Blocks to all classes
2. Fixed small bugs in \GoogleUrl\ProxyPool\File
2. Class \GoogleUrl\Exception\CaptachaException renamed to \GoogleUrl\Exception\CaptchaException

### CODE REVIEW

**Comment by SneakyBobito** [comment]
Thanks a lot for the PR, I'll take a few time before i merge it because a new version is almost ready : https://github.com/SneakyBobito/google-url/tree/dev-v2

I will merge it into v2 directly. Maybe can you help me if you rebase your branch on the ``dev-v2`` one and make the pull request on this branch ?

Thank for your interest in this library

**Comment by Glorian** [comment]
Okay, I'll do it after a while.

**Comment by SneakyBobito** [comment]
Thank you, just a correction, when I write "on this branch" i mean, PR on the ``dev-v2`` branch

**Comment by SneakyBobito** [comment]
Hi, how are you doing with it ?
If  you dont have time just tell me I'll handle it.

**Comment by SneakyBobito** [comment]
I close the PR, open an other one if you want to merge updated content

**Pull request closed without merging**
